/**
 * Lucide icon assignments per medical specialty. Used by MediaTile to
 * render a semantic icon tile in place of a stock photo. Each icon is
 * chosen for direct visual association with the specialty's domain.
 *
 * If a specialty isn't listed, the consumer should default to `Stethoscope`.
 */
import {
    Activity,
    Baby,
    Bone,
    Brain,
    Droplet,
    Ear,
    Eye,
    HandHeart,
    Heart,
    Hospital,
    Microscope,
    Pill,
    Scissors,
    ShieldCheck,
    Smile,
    Sparkles,
    Stethoscope,
    Syringe,
    TestTube,
    Thermometer,
    UserRound,
    Wind,
    Zap,
    type LucideIcon,
} from 'lucide-react';

import {
    BookOpen,
    Briefcase,
    Building2,
    ClipboardList,
    Compass,
    FileText,
    FlaskConical,
    Globe2,
    GraduationCap,
    HelpCircle,
    LayoutGrid,
    LifeBuoy,
    Mail,
    MapPin,
    MessageCircle,
    Newspaper,
    Phone,
    Search,
    Shield,
    Users,
    Wallet,
} from 'lucide-react';

/* ─── Specialty → Lucide icon ───────────────────────────── */
export const SPECIALTY_LUCIDE_ICON: Record<string, LucideIcon> = {
    'Cardiology': Heart,
    'Cardiothoracic & Vascular Surgery': Heart,
    'Vascular Surgery': Heart,
    'Neurology': Brain,
    'Neurosurgery': Brain,
    'Dermatology': Sparkles,
    'Plastic Surgery': Scissors,
    'Plastic & Reconstructive Surgery': Scissors,
    'Ophthalmology': Eye,
    'Dentistry': Smile,
    'Maxillofacial & Oral Surgery': Smile,
    'Hematology': Droplet,
    'Hematology / Oncology': Droplet,
    'Pathology': Microscope,
    'Nephrology': Droplet,
    'Urology': Droplet,
    'Endocrinology': Activity,
    'Allergy & Immunology': ShieldCheck,
    'Infectious Disease': Thermometer,
    'Gastroenterology': Pill,
    'Hepatology': Pill,
    'Geriatrics': UserRound,
    'Palliative Care': HandHeart,
    'Pain Medicine & Palliative Care': HandHeart,
    'Sleep Medicine': UserRound,
    'Psychiatry': Brain,
    'Psychiatry & Mental Health': Brain,
    'Radiology': Microscope,
    'Nuclear Medicine': Zap,
    'Radiation Oncology': Zap,
    'Orthopedic Surgery': Bone,
    'Orthopedics': Bone,
    'Rheumatology': Bone,
    'Sports Medicine': Activity,
    'Physical Medicine & Rehabilitation': Activity,
    'Anesthesiology': Syringe,
    'General Surgery': Scissors,
    'Pulmonology': Wind,
    'ENT (Ear, Nose, Throat)': Ear,
    'Pediatrics': Baby,
    'Neonatology': Baby,
    'Family Medicine': Stethoscope,
    'Obstetrics & Gynecology': UserRound,
    'Preventive Medicine': ShieldCheck,
    'Preventive & Public Health': ShieldCheck,
    'Tropical Medicine': Globe2,
    'Occupational Medicine': Briefcase,
    'General Medicine': Stethoscope,
    'Internal Medicine': Stethoscope,
    'Emergency Medicine': Activity,
    'Oncology': TestTube,
    'Pain Management': HandHeart,
    'Immunology': ShieldCheck,
    'Genetics': FlaskConical,
    'Podiatry': Bone,
};

export function getSpecialtyLucideIcon(specialty: string | null | undefined): LucideIcon {
    if (!specialty) return Stethoscope;
    return SPECIALTY_LUCIDE_ICON[specialty] || Stethoscope;
}

/* ─── Treatment / category → Lucide icon ────────────────── */
export const TREATMENT_LUCIDE_ICON: Record<string, LucideIcon> = {
    surgery: Scissors,
    operatingRoom: Hospital,
    radiology: Microscope,
    imaging: Microscope,
    pills: Pill,
    pharmacy: Pill,
    medication: Pill,
    recovery: Heart,
    lab: TestTube,
    diagnostics: FlaskConical,
    wellness: Sparkles,
    rehab: Activity,
    fitness: Activity,
    consultation: Stethoscope,
    telehealth: Stethoscope,
};

/* ─── Marketing page kind → Lucide icon ─────────────────── */
export const PAGE_LUCIDE_ICON: Record<string, LucideIcon> = {
    home: Compass,
    about: Newspaper,
    blog: BookOpen,
    careers: GraduationCap,
    contact: Mail,
    advertise: Briefcase,
    'for-doctors': Stethoscope,
    'editorial-board': ClipboardList,
    faq: HelpCircle,
    help: LifeBuoy,
    book: ClipboardList,
    conditions: LayoutGrid,
    treatments: Pill,
    'diagnostic-labs': FlaskConical,
    'clinical-reference': BookOpen,
    insurance: Shield,
    hospitals: Building2,
    doctors: UserRound,
    pricing: Wallet,
    symptoms: Activity,
    search: Search,
    location: MapPin,
    phone: Phone,
    chat: MessageCircle,
    docs: FileText,
    team: Users,
};

export function getPageLucideIcon(slug: string): LucideIcon {
    return PAGE_LUCIDE_ICON[slug] || Compass;
}
