import { NextRequest, NextResponse } from 'next/server';
import { translateConditionContent } from '@/lib/translate-condition-content';
import { verifyAdminAuth } from '@/lib/admin-auth';

/**
 * POST /api/translate-condition
 *
 * ADMIN ONLY. Hits a paid LLM provider; left open it's a pure cost-burn
 * vector. Translation fallback for end users should be pre-generated by
 * a scheduled job, not produced live on a request.
 */
const SUPPORTED_LANGS = new Set([
    'hi','ar','bn','de','es','fr','gu','kn','ml','mr','or','pa','pt','ta','te','ur',
]);

export async function POST(req: NextRequest) {
    const auth = await verifyAdminAuth(req);
    if (!auth.authenticated) {
        return NextResponse.json({ ok: false, error: 'Unauthorized' }, { status: 401 });
    }
    try {
        const { conditionId, targetLang } = await req.json();

        if (!conditionId || typeof conditionId !== 'number') {
            return NextResponse.json({ ok: false, reason: 'invalid conditionId' }, { status: 400 });
        }
        if (!targetLang || typeof targetLang !== 'string' || !SUPPORTED_LANGS.has(targetLang)) {
            return NextResponse.json({ ok: false, reason: 'invalid targetLang' }, { status: 400 });
        }

        // Run translation (this may take 10-30 seconds for a full page)
        const created = await translateConditionContent(conditionId, targetLang);

        return NextResponse.json({ ok: true, created });
    } catch (error) {
        console.error('[api/translate-condition]', error);
        return NextResponse.json({ ok: false, error: 'translation failed' }, { status: 500 });
    }
}
